# Generated by Django 2.2.5 on 2022-09-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administer_data', '0002_auto_20220830_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lecture_content', models.CharField(max_length=20)),
                ('is_target_old', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.TextField(max_length=200)),
                ('faves', models.IntegerField(blank=True, default=0)),
                ('author', models.CharField(blank=True, default='名無し', max_length=20)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administer_data.ClassInfo')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('prefecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administer_data.Prefecture')),
            ],
        ),
        migrations.AddField(
            model_name='classinfo',
            name='city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='administer_data.City'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='lecture',
            field=models.ManyToManyField(related_name='class_info', to='administer_data.Lecture'),
        ),
    ]
