# Generated by Django 3.2.15 on 2022-10-01 01:39
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    path = "administer_data/fixtures/"
    call_command('loaddata', path+'min_required.json', app_label='administer_data')
    call_command('loaddata', path+'pref47.json', app_label='administer_data')


class Migration(migrations.Migration):

    dependencies = [
        ('administer_data', '0002_auto_20221001_0942'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
