# Generated by Django 3.2.15 on 2022-10-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administer_data', '0002_auto_20221001_0942'),
    ]

    operations = [
    ]
