# Generated by Django 2.2.5 on 2022-09-12 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administer_data', '0004_auto_20220910_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='city',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='administer_data.City'),
        ),
    ]
