# Generated by Django 3.2.15 on 2022-10-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administer_data', '0004_auto_202210232214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('url', models.URLField()),
            ],
        ),
    ]
