# Generated by Django 3.2.15 on 2022-10-23 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administer_data', '0004_auto_202210232214'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='class_organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='administer_data.classorganizer'),
        ),
    ]
