# Generated by Django 2.2.5 on 2022-09-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administer_data', '0005_auto_20220912_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='prefecture',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='administer_data.Prefecture'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='administer_data.City'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_content',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='pref_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
