# Generated by Django 3.2.15 on 2022-10-01 01:39
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


def load_fixture(apps, schema_editor):
    path = "administer_data/fixtures/"
    call_command('loaddata', path+'min_required.json', app_label='administer_data')
    call_command('loaddata', path+'pref47.json', app_label='administer_data')
    call_command('loaddata', path+'sampledata.json', app_label='administer_data')
    call_command('loaddata', path+'tokyo-utf-test.json', app_label='administer_data')
    call_command('loaddata', path+'additional_lecture.json', app_label='administer_data')
    call_command('loaddata', path+'addtional_upcome_lec.json', app_label='administer_data')


class Migration(migrations.Migration):

    dependencies = [
        # 最期のmigrationsに接続するように書き換える
        ('administer_data', '0004_auto_20221202_0022'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
